### ISSUE TITLE
AppleALC and VoodooHDA as kext

### ISSUE THREAD

**Issue by rafaelmaeuer** [Qraxin/Asus-P8P67-OpenCore-EFI#2]
Is there a reason you added AppleALC and VoodooHDA as kexts?
When running OpenCore SanityCheck it complains about only choosing one of these kexts:

<img width="650" alt="Bildschirmfoto 2021-01-19 um 20 32 57" src="https://user-images.githubusercontent.com/6418459/105083690-8f8de480-5a95-11eb-8a0f-2cd7bc46d3aa.png">

**Comment by Qraxin** [comment]
Hey @rafaelmaeuer,  you are right. The AppleALC kext is no need. I removed it from folder. Thanks.
